.TH gameconqueror 1 "2016-07-27" "" ""
.SH NAME
gameconqueror \- A GUI for scanmem, a game hacking tool.

.SH SYNOPSIS
.B gameconqueror
.RB [options]
.IR [target-program-pid]

.SH DESCRIPTION
.PP
Scanmem is a simple interactive debugging utility for Linux, used to locate the
address of a variable in a running process. This can be used for the analysis or
modification of a hostile process on a compromised machine, for reverse
engineering, or as a "pokefinder" to cheat at video games.
.PP
GameConqueror is a GUI for scanmem, aims to provide more features than scanmem,
and CheatEngine-alike user-friendly interface.
.PP

.SH OPTIONS

.B "\-v, \-\-version"

Print version and exit.

.B "\-h, \-\-help"

Print a short description of command line options and exit.

.BI "\-s, \-\-search=" value

Fill the search box with the given
.IR value "."

.SH HOMEPAGE
https://github.com/scanmem/scanmem

.SH AUTHOR
gameconqueror has been written by WANG Lu <coolwanglu@gmail.com>. See copyright
file for full list of authors.
.PP
This manual page has been written by Kartik Mistry <kartik@debian.org>, for the
Debian project (but may be used by others).

.SH SEE ALSO
scanmem(1)
