name: linux-setup
description: Set up the Linux VM

runs:
  using: 'composite'
  steps:
    - run: pwd
      shell: bash
    - run: ls -lhaR .github/
      shell: bash
    - run: git branch -a
      shell: bash
    - run: touch 01-linux-setup
      shell: bash
    - run: sudo apt --assume-yes update
      shell: bash
    - run: sudo apt --assume-yes upgrade
      shell: bash
    - run: sudo apt --assume-yes autoremove
      shell: bash
    - run: sudo apt --assume-yes install make gcc binutils intltool libtool autotools-dev libreadline-dev python3
      shell: bash
    - run: ls -lha .
      shell: bash
