name: linux-setup
description: Set up the Linux VM

runs:
  using: 'composite'
  steps:
    # Linux version
    - run: lsb_release -a
      shell: bash
    # Update packages
    - run: sudo apt --assume-yes update
      shell: bash
    # Upgrade packages
    - run: sudo apt --assume-yes upgrade
      shell: bash
    # Auto-remove packages
    - run: sudo apt --assume-yes autoremove
      shell: bash
    # Install required packages
    - run: sudo apt --assume-yes install make gcc binutils intltool libtool autotools-dev libreadline-dev python3
      shell: bash
