name: linux-setup
description: Set up the Linux VM

runs:
  using: 'composite'
  steps:
    # Linux version
    - run: uname -a
    # Linux version
    - run: lsb_release -a
    # Current directory
    - run: pwd
    # Github actions
    - run: ls -lhaR .github/
    # Github branch
    - run: git branch -a
    # Create file
    - run: touch 01-linux-setup
    # Update packages
    - run: sudo apt --assume-yes update
    # Upgrade packages
    - run: sudo apt --assume-yes upgrade
    # Auto-remove packages
    - run: sudo apt --assume-yes autoremove
    # Install required packages
    - run: sudo apt --assume-yes install make gcc binutils intltool libtool autotools-dev libreadline-dev python3
    # List file
    - run: ls -lha .
