name: testing
run-name: Testing by ${{ github.actor }}

on: [push,workflow_dispatch]

jobs:
  testing:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Linux set up
        uses: ./.github/actions/linux-setup
      - name: Make the binary
        run: make CFLAGS='-O2 -fsanitize=address,undefined'
      - name: Testing requires `sudo` for `ptrace()`
        run: sudo make check VERBOSE=1
      - name: Testing
        run: cd test && ./sm_test.sh
