name: build-gui
run-name: Build GUI by ${{ github.actor }}

on: [push,workflow_dispatch]

jobs:
  build-gui:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Linux set up
        uses: ./.github/actions/linux-setup
      - name: Run auto-generate
        run: ./autogen.sh
      - name: Run the configuration
        run: ./configure --enable-gui
      - name: Make the binary
        run: make CFLAGS='-O2 -fsanitize=address,undefined'
      - name: Testing requires `sudo` for `ptrace()`
        run: make check VERBOSE=1
      - name: Install Scanmem
        run: sudo make install
